# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=b'', max_length=200)),
                ('description', models.CharField(default=b'', max_length=1000)),
                ('publish_date', models.CharField(default=b'', max_length=200)),
                ('publish_status', models.CharField(choices=[(b'D', b'Draft'), (b'P', b'Published')], default=b'D', max_length=1)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_images', to='look.Look')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(default=b'', max_length=200)),
                ('price', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coor_x', models.FloatField(default=0)),
                ('coor_y', models.FloatField(default=0)),
                ('look_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='look.LookImage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='look.Product')),
            ],
        ),
    ]
