# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to=settings.AUTH_USER_MODEL),
        ),
    ]
