# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0006_auto_20190814_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_old',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
