# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0009_lookimage_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookimage',
            name='image_thumbnail',
            field=models.ImageField(default=b'default/logo_transparent.png', upload_to=b''),
        ),
    ]
