# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 00:05
from __future__ import unicode_literals

from django.db import migrations
from PIL import Image
import tempfile
import os
import boto3

def gen_image_thumbnail(apps, schema_editor):
    MyModel = apps.get_model('look', 'LookImage')
    print ''
    for look in MyModel.objects.all():
        s3 = boto3.resource('s3', region_name='us-east-2')
        bucket = s3.Bucket('eastyler-static')
        print 'media/'+look.image.__str__()
        object = bucket.Object('media/'+look.image.__str__())
        try:
            response = object.get() 
        except Exception as e:
            print e
            continue
        
        file_stream = response['Body']
        imageTemproary = Image.open(file_stream)
        imageTemproary = imageTemproary.convert('RGB')
        imageTemproary.thumbnail((600, 900), Image.ANTIALIAS) 
        compressed_image = tempfile.SpooledTemporaryFile()
        imageTemproary.save(compressed_image , format='JPEG', quality=100, progressive=True, optimize=True)

        url = look.image.__str__()
        name, extension = os.path.splitext(url)

        new_url = name + '-thumbnail' + extension
        print "saving new url:", new_url
        look.image_thumbnail.save(new_url, compressed_image)
        look.save()


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0010_auto_20190822_0429'),
    ]

    operations = [
        migrations.RunPython(gen_image_thumbnail, reverse_code=migrations.RunPython.noop),
    ]
