# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'This display name has already been registered.'}, max_length=50, unique=True),
        ),
    ]
