# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 22:36
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190814_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='user_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True),
        ),
    ]
