# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('S', 'Self'), ('F', 'Friend')], default='S', max_length=1),
        ),
    ]
