# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-14 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200)),
                ('credit', models.CharField(default=b'', max_length=200)),
                ('credit_link', models.URLField(default=b'')),
                ('description', models.CharField(default=b'', max_length=1000)),
                ('tags', models.CharField(default=b'', max_length=200)),
                ('publish_date', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_images', to='style.Style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('coor_x', models.FloatField(default=0)),
                ('coor_y', models.FloatField(default=0)),
                ('title', models.CharField(default=b'', max_length=200)),
                ('price', models.CharField(default=b'', max_length=200)),
                ('style_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_image_annotations', to='style.StyleImage')),
            ],
        ),
    ]
