# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('coor_x', models.FloatField()),
                ('coor_y', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='style',
            name='style_image_url',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='styleimageannotation',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style.Style'),
        ),
    ]
