# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_style_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
