# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_auto_20181110_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='credit',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='style',
            name='credit_link',
            field=models.URLField(default=b''),
        ),
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='style',
            name='publish_date',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='style',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_image_url',
            field=models.URLField(default=b''),
        ),
    ]
