# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-03 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('style', '0004_auto_20181111_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
