# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0005_style_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='tags',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='styleimageannotation',
            name='price',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='styleimageannotation',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
