# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-19 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0006_auto_20190519_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleimageannotation',
            name='coor_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='styleimageannotation',
            name='coor_y',
            field=models.FloatField(default=0),
        ),
    ]
